### ISSUE TITLE
Peer Review 1

### ISSUE THREAD

**Issue by jeno0403** [moonsdust/toronto-homicides-shootings#1]
**Opening Statement Summary:**
This project aims to analyze homicides and shootings in Toronto by examining both their spatial distribution and temporal trends. Using publicly available data from the City of Toronto’s Open Data Portal, the study provides insights into geographic patterns and fluctuations in crime rates across the city.

**Strong Positive Points:**
The use of R for data cleaning, simulation, and visualization is effective, particularly the clear distinction between raw and processed datasets—additionally, a well-put effort on the sketch. Sketches are wonderful and convey a strong message.

**Critical Improvements Needed:**
Remark on the reference section on paper. More references must be considered to integrate into this paper to show a certain sense of credibility. Also please revise the README file by providing a concise overview of the project and make sure it is as informative as possible to ensure reproducibility. 

**Suggestions for Improvement:**
The README could benefit from a more structured and informative format. Rather than offering general advice, focus on outlining specific steps and processes used in the project, including detailed instructions on data cleaning, simulation, and visualization. This will make the project more accessible and ensure reproducibility for other users.

**Evaluation:**
If I were to grade this section, I would assign a score of 80. The file names in the repository are descriptive and facilitate easy navigation, such as distinguishing between raw and clean data. In the code, variable names are meaningful and consistent, aiding comprehension.
**Estimated Mark:**
79
**Reason:**
The data collection and cleaning processes in the project seem appropriate. The distinction between raw and clean data is especially helpful for navigating the repository. However, improvements to the README and more references in the paper could elevate the work.

**Comment by moonsdust** [comment]
Thank you for the review! These have been addressed.
