### ISSUE TITLE
Peer review #2

### ISSUE THREAD

**Issue by karenrni** [moonsdust/toronto-homicides-shootings#2]
This is a great start for a website but just needs a bit more work!

### Strong positive points
Your GitHub is well structured and the important files are appropriately named. The sketches are nicely done and informative, overall they are above expectation.  The cleaning and downloading code is nicely and clearly formatted, making it easy to understand with informative commits.

### Critical improvements needed:

The paper is missing critical details and sections regarding information on the analysis and data, introductions, conclusions, abstracts, graphs and proper citation. Missing data simulation code and test code. 

### Suggestions for improvement:

Adding missing information in relevant areas, renaming ambiguous files, deleting excess or unrelated data and reviewing/ complete the final paper. Take special care of the format in terms of citation. Missing large chunks of paper sections should be addressed. 

Adding a little overview for the README.

Evaluation:

### Estimated mark:
I have gone through and added each component  resulting with an estimated 18/100

Reason:
It needs more work like including more detailed information in the ReadMe, adding missing analysis, discussion and results, and must develop clear and informative graphs. However, this is already a solid foundation with potential to be great!!

**Comment by karenrni** [comment]
Specifically,

R is appropriately cited- 1
LLM usage is documented-1
Title-1
Author, date, and repo-2
Abstract-0
Introduction-0
Data-6
Measurement-0
Prose-1
Cross-references-0
Captions-0
Graphs/tables/etc-0
Referencing-0
Commits-2
Sketches-2
Simulation-0
Tests-0
Reproducibility-1
Code style-0
General excellence-1

**Comment by moonsdust** [comment]
Thank you for the feedback! These have been addressed.
